artifact_uri: file:///c:/Users/moham/Desktop/fly/FlyPrice-main/mlflow_tracking/977363302318645728/3c41891b53dc47528684db48ed735adb/artifacts
end_time: 1772484852790
entry_point_name: ''
experiment_id: '977363302318645728'
lifecycle_stage: active
run_id: 3c41891b53dc47528684db48ed735adb
run_name: XGBoost_Flight_Price_Prediction
source_name: ''
source_type: 4
source_version: ''
start_time: 1772484847911
status: 3
tags: []
user_id: talent
