artifact_uri: file:///c:/Users/moham/Desktop/fly/FlyPrice-main/mlflow_tracking/977363302318645728/bb720c40fc76420da09f3756710089a7/artifacts
end_time: 1772484963753
entry_point_name: ''
experiment_id: '977363302318645728'
lifecycle_stage: active
run_id: bb720c40fc76420da09f3756710089a7
run_name: LinearRegression_Flight_Price_Prediction
source_name: ''
source_type: 4
source_version: ''
start_time: 1772484961130
status: 3
tags: []
user_id: talent
