artifact_location: file:///c:/Users/moham/Desktop/fly/FlyPrice-main/mlflow_tracking/0
creation_time: 1772484377601
experiment_id: '0'
last_update_time: 1772484377601
lifecycle_stage: active
name: Default
workspace: default
