artifact_location: file:///c:/Users/moham/Desktop/fly/FlyPrice-main/mlflow_tracking/399845703339514782
creation_time: 1772484690986
experiment_id: '399845703339514782'
last_update_time: 1772484690986
lifecycle_stage: active
name: Flight_Price_Prediction
workspace: default
